### ISSUE TITLE
2024 Q2 Event - Video Recording and Post-production

### ISSUE THREAD

**Issue by allella** [hackgvl/nights#22]
## Volunteers

- Olivia Sculley
- Joey Loman
- Matt Thornton

## Tasks
- [x] Record videos
- [x] [Post-production work](https://github.com/hackgvl/nights/issues/5#issuecomment-2005610028)
- [x] Upload to online channel

## Notes
Joey Loman may be willing to lend equipment to record the events.  Olivia handled the editing and YouTube uploading

**Comment by allella** [comment]
It looks like the videos are getting viewed https://www.youtube.com/@HackGreenville/videos

@oliviasculley @jhloman @ThorntonMatthewD thoughts on the video recording for HG Nights?

**Comment by jhloman** [comment]
> @oliviasculley we have the schedule published and the talks will be a single track, so we'd expect a single video camera would suffice.
> 
> Are you still willing and able to handle the video recording and post production for this event?
> 
> Thanks

Yes for me supplying the gear, no for me in attendance. I will have the equipment ready to pick up from my office at SynergyMill, camera, tripod, supporting gear. The unfortunate fact for me is that I will be out of town that week, my apologies.

**Comment by oliviasculley** [comment]
I'll be attending, and since it seems like there's a single track, I can handle recording and editing like last time! If we're using the camera's built-in microphones again, I'll be attempting to use Adobe's free AI Podcasting software to assist with the audio quality and documenting the procedure.

**Comment by allella** [comment]
Thanks.

We may have the talks inside of OpenWorks to have a more quite space. So, the sound should be better because the glass there is double-pane.

We'll see. If we end up using the conference rooms, then we may need to at least sale the gaps between the glass, if not put up curtains.
