### ISSUE TITLE
2024 Q2 - Highlight Meetup Groups and Community Orgs with a Whiteboard / Table

### ISSUE THREAD

**Issue by allella** [hackgvl/nights#26]
Jas offered to setup an area to [highlight the local meetup groups at a table, whiteboard, etc.](https://github.com/hackgvl/nights/issues/3#issuecomment-1942526479)

### Tasks

- [ ] Whiteboard - a rolling whiteboard available from the conference rooms at OpenWorks
- [ ] Table - we can use one of the white rolling tables that will be removed from the conference rooms

**Comment by allella** [comment]
@chruck are you good to manage the promo / whiteboard area at HG Nights on May 16?

If so, any tweaks or suggestions?

**Comment by chruck** [comment]
Goodness, I didn't realize it was coming up next week!

Yeah, I'll be glad to do it again.

- Was the location good last time?
- Any suggestions for improvements, or problems with previous?

--Jas Eckard
 .
..:

**Comment by allella** [comment]
Great.


It's possible that we have the talks inside of OpenWorks for the noise separation.  

If we do that, then we'd have more room in the round table area, so I think we could put the whiteboard and some stuff along the glass wall looking into OpenWorks to be more noticeable and possibly as a visual break.

I didn't hear much feedback one way or another, but I think it would be worth asking in #community-organizers to get feedback and interest.
