### ISSUE TITLE
2024 Q3 Event - Video Recording & Post-production

### ISSUE THREAD

**Issue by allella** [hackgvl/nights#33]
See our earlier [Video and Post-production](https://github.com/hackgvl/nights/issues?q=video+in%3Atitle+is%3Aissue) issues for past notes and context.

## Past Volunteers
- Olivia Sculley
- Joey Loman
- Matt Thornton

## Tasks
- [x] Record videos
- [x] Post-production work
- [x] Upload to online channel

**Comment by allella** [comment]
@oliviasculley we're planning to do the talks inside OpenWorks again to keep the social noise from interfering with the talks.

Do you have any needs or suggestions for Tuesday on the video side?

**Comment by oliviasculley** [comment]
No, we should be all good!

**Comment by allella** [comment]
Thanks so much for knocking it out of the park.

Let me know anything we should be telling the presenters and we'll make note of it for next time.

Asking them to repeat questions during Q&A is the one suggestion.
