### ISSUE TITLE
2024 Q1 Event - Video Recording and Post-production

### ISSUE THREAD

**Issue by allella** [hackgvl/nights#5]
## Volunteers

- Olivia Sculley
- Joey Loman
- Matt Thornton

## Tasks
- [x] Record videos
- [x] [Post-production work](https://github.com/hackgvl/nights/issues/5#issuecomment-2005610028)
- [x] Upload to online channel

## Notes
Joey Loman may be willing to lend equipment to record the events.  Olivia may have offered to assist with some part of the recording or equipment.

We're not talking about live streaming, but posting videos online after an event.

This is likely more interesting if there are multiple tracks, so people can catch a talk that they missed.

HG doesn't have a YouTube, so we'd need to get that setup if talks were to be posted under the HG brand.

Joey thumbs up the suggestion.

![image](https://github.com/hackgvl/nights/assets/1777776/c3a99c9e-9eb8-432c-93b6-a04fa8b00337)

**Comment by allella** [comment]
@oliviasculley @jhloman we're going to ask the presenters to bring their own HDMI to TV adapters.

I know we're not trying to get involved in recording things on their device, but I did want to have a plan to have backup adapters for people's laptops in the event they forget to bring one.

This happened at the pilot event.

Do you have a reasonable set of Apple and non-Apple adapters that are easy to bring and have on hand?  

OpenWorks has some older adapters, like D-port to HDMI and some old Apple adapters (not Lighting or current models).

No pressure, but figured I'd ask since you folks seem to have a lot of video gadgets.

**Comment by avon61002** [comment]
Just throwing this out there: I've been meaning to record an video demonstration of Briar for a while now, and I think it would be neat if I could append a quick demo of the core features at the end of my talk recording (or maybe as a companion video on the briar or hackgvl youtube?). I think it would be really useful for folks that couldn't make it to the in-person event. I could handle the editing/recording on my own.

**Comment by oliviasculley** [comment]
That's totally doable, we can coordinate on Slack about this after the event!

**Comment by allella** [comment]
@oliviasculley @jhloman is there anything we can do to help you two with the video?

A minor change, but here's the room setup given the size of the group (up to 85 registered).

We're opening the two conference rooms so they are one bigger room.

- Session 1: Gavin and Paul will lead us off in this combined conference room.
- Breakout: Room 1:  Christina, Bogdan and I will utilize the round table area in front of the kitchen and the wall mounted TV.
- Breakout: Room 2: Jas, Brian, and Pam will also be in the big conference room for the breakouts.

I'll be there are early as 4 PM and other volunteers are arriving around 4:30 - 5 PM.

Feel free to come as early as you want if you'd like to hang out at OW and get some work done.

Wi-Fi info is under the glass on the printer table between the two refrigerators inside OpenWorks.

**Comment by oliviasculley** [comment]
We're all good, I'll be finding a volunteer for the second breakout room at the event, most likely will be some of the people who have already volunteered :smile:

**Comment by allella** [comment]
Sounds like @ThorntonMatthewD, if he makes it.  If not, the other volunteers are listed at https://github.com/hackgvl/nights/issues/6

**Comment by ThorntonMatthewD** [comment]
I will be there! I will not be able to make it in time for setup prior to 6, however.

**Comment by oliviasculley** [comment]
I still need to edit the videos, but is there a particular location that you would like the videos to end up @pamelawoodbrowne @eric-hemasystems @bogdankharchenko? I'm hoping to get them all edited by tonight, maybe with exception of the Briar one until I can get the footage to edit in with the main presentation

**Comment by avon61002** [comment]
> maybe with exception of the Briar one until I can get the footage to edit in with the main presentation

Feel free to post just the talk, I'm going to record and edit the Briar demos separately and talk w the team to see if it would make sense to post it on the official briar youtube. We could maybe edit the description of the presentation video to link to the demo recordings. For now it might be useful to just link demos done by other members of the community like this one which is pretty great: https://www.youtube.com/watch?v=AzJrd0Doz0M

Thanks!

**Comment by pamelawoodbrowne** [comment]
I don't think we have a HackGreenville YouTube account yet.

**Comment by allella** [comment]
@pamelawoodbrowne Olivia was bringing it up [because of the related message I mentioned in meta about needing some other things](https://github.com/hackgvl/meta/issues/21#issuecomment-1965275037)(email, registering accounts with either an accounts@ or similar), saving that in a p w d manager and then sharing / delegating permissions in various services.

Robert did start messing with a mailing list on the Google Workspace, so that will likely still be an option, but even an @hackgreenville.com email address would help move things along.

**Comment by allella** [comment]
We could certainly create a service under a temporary email address, but that's one more thing someone needs to transfer back into the @hackgreenville.com and p w d manager, so it may save some work to get this stuff registered under HG ownership / email from the start.

**Comment by allella** [comment]
![image](https://github.com/hackgvl/nights/assets/1777776/421eb7a9-939e-4686-bc9c-263be26828c9)

**Comment by allella** [comment]
Kudos again to @oliviasculley and @jhloman for recording.

Thanks to @oliviasculley for the editing and uploading.

Thanks @eric-hemasystems for setting up a [new HG YouTube channel](https://www.youtube.com/@HackGreenville).
